# -*- coding: utf-8 -*-
"""Inferencia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WjfUp8Qa9YShj9ebdYrq-Tq49PGnFVWH
"""

import joblib
import numpy as np
import pandas as pd
from procesamiento_datos import procesar_data, NeuralNetworkTensorFlow  # Función de preprocesamiento definida y clase de NN

# Cargamos el modelo entrenado y el escalador usando joblib

modelo = joblib.load('best_model.pkl')
scaler = joblib.load('scaler.pkl')

def inferencia(input_file, output_file):

    # Paso 1: Leer el archivo CSV de entrada
    input_data = pd.read_csv(input_file)

    # Paso 2: Preprocesamiento de los datos (imputación, codificación, etc.)
    input_data_processed = procesar_data(input_data)  # Llamamos a la función de procesamiento

    # Paso 3: Escalar los datos usando el scaler cargado
    input_data_scaled = scaler.transform(input_data_processed)  # Normalizamos o escalamos los datos

    # Paso 4: Hacer la predicción con el modelo cargado
    predictions = modelo.predict(input_data_scaled)  # Realizamos la predicción

    # Paso 5: Guardar las predicciones en un archivo CSV de salida
    output_data = input_data.copy()  # Copiamos los datos originales para mantener las columnas
    output_data['predictions'] = predictions  # Añadimos una columna con las predicciones

    # Guardar el archivo de salida con las predicciones
    output_data.to_csv(output_file, index=False)
    print(f'Inferencia realizada. Resultados guardados en {output_file}')
